### ISSUE TITLE
Image dosen't run flask

### ISSUE THREAD

**Issue by Rafael-Sampaio-Pereira** [Tecktron/docker-python-bjoern#1]
I had build my image and i'm trying run my flask app with:

$ docker run  -p 8080:8080 -e DEBUG="True" -e APP_MODULE="server:application" myimage

Nothing happened. Only the prestart.sh has be processed.

Any idea?

**Comment by Tecktron** [comment]
What is the structure of your project? 

As given, if you are copying your path into the `/app` dir, it will be expecting there to be a file named `server.py` in the project root which contains a WSGI variable called `application`. 


Here's an example that hopefully will clear things up for you. 

Suppose you have a server.py file as such:
```
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"
```

If you have server.py in the root, it would look like this:
```
/
- server.py
```
Then
`APP_MODULE="server:app"`

If you have server.py within a package you would need to specify the package as well. 

```
/
+ my_app
- - __init__.py
- - server.py
```
Then:
`APP_MODULE="my_app.server:app"`

You can also specify this in the Docker file itself so you don't want to pass this in on the command line. 

For example:
```
FROM tecktron/python-bjoern:latest

ENV APP_MODULE=my_app.server:app

COPY . /app
WORKDIR /app/

RUN python -m pip install flask
```

**Comment by Rafael-Sampaio-Pereira** [comment]
yes, my server file is in root. Im run like you have showed, but it still not working. 

it just works if a put   api.run(HOST, PORT, threaded=True) at the end of my server.py file.. but i think this is wrong way to run flask in production envirioments.

Thank you so much for your help!!!

**Comment by Tecktron** [comment]
I've tested this out and I have found 2 things.

The first is a bug on my end that is preventing the output to the console. I have identified the issue and will have the fix out very shortly on all versions.

The second I see is your docker call, specifically the port.

Bjoern is setup to run on port 80 inside the container so you need to adjust your call:
`$ docker run -p 8080:80 -it -e DEBUG="True" -e APP_MODULE="server:application" myimage`
To run on localhost:8080

If you want to change the port within the container (for whatever reason) you would need to pass in the `BJOERN_PORT` variable to have it run on whatever port you want. 
`$ docker run -p 8080:8080 -it -e DEBUG="True" -e APP_MODULE="server:application" -e BJOERN_PORT=8080 myimage`

**Comment by Rafael-Sampaio-Pereira** [comment]
Thank you again for your quick response. I'll be waiting for  this bug fix. see you.

**Comment by Tecktron** [comment]
@Rafael-Sampaio-Pereira The output issue has been resolved and updated on docker hub.

Please be sure to pull the image before you build to make sure you get the update.

I also pushed the very simple demo project I used in case it has value for you: 
https://github.com/Tecktron/docker-bjoern-flask-demo

**Comment by Rafael-Sampaio-Pereira** [comment]
Now its working fine. Thanks one more time.
